config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  get "cart" => "cart#show"
  get "cart/add/:id" => "cart#add", :as => :add_to_cart
  post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
  post "cart/checkout" => "cart#checkout", :as => :checkout

  get 'signup' => 'users#new', :as => :signup
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'login' => 'sessions#new', :as => :login
  resources :sessions
  resources :users
  resources :products

  root :to => "sessions#new"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :order, foreign_key: :order_id
  belongs_to :user

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  has_one :appointment, :dependent => :destroy
  belongs_to :user

  scope :in_progress, ->{where("orders.checked_out_at IS NULL")}
  scope :complete, -> {where("orders.checked_out_at IS NOT NULL")}

  COMPLETE = "complete"
  IN_PROGRESS = "in_progress"

  def self.find_with_product(product)
    return [] unless product
    complete.joins(:line_items).
        where(["line_items.product_id = ?", product.id]).
        order("orders.checked_out_at DESC")
  end



  def checkout!
    self.checked_out_at = Time.now
    self.save
  end

  def recalculate_price!
    self.total_price = line_items.inject(0.0){|sum, line_item| sum += line_item.price }
    save!
  end

  def state
    checked_out_at.nil? ? IN_PROGRESS : COMPLETE
  end

  def display_name
    ActionController::Base.helpers.number_to_currency(total_price) +
        " - Order ##{id} (#{user.username})"
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

  # Named Scopes
  scope :available, lambda{ where("available_on < ?", Date.today) }
  scope :drafts, lambda{ where("available_on > ?", Date.today) }

  # Validations
  validates_presence_of :title
  validates_presence_of :price


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders, :dependent => :destroy
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true
  validates_format_of :username, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
  validates :username, presence: true, uniqueness: true, length: { maximum: 30 }
  validates :phone, format: { with: /\d{3}-\d{3}-\d{4}/, message: "- Please enter phone number in xxx-xxx-xxxx format" }
  validates :email, presence: true, format: { with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i, message: "- Email must be in xxxx@xxxxxx.com format" }, uniqueness: true, length: { maximum: 50 }



  attr_accessor :password
  before_save :prepare_password
=begin
  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /(?=.*[A-Za-z._@])/, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true
=end
  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.matching_password?(pass)
  end

  def matching_password?(pass)
    self.password_hash == encrypt_password(pass)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = Digest::SHA1.hexdigest([Time.now, rand].join)
      self.password_hash = encrypt_password(password)
    end
  end

  def encrypt_password(pass)
    Digest::SHA1.hexdigest([pass, password_salt].join)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  protect_from_forgery
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_filter :login_required
  before_filter :find_cart

  def add
    @cart.save if @cart.new_record?
    session[:cart_id] = @cart.id
    product = Product.find(params[:id])
    LineItem.create! :order => @cart, :product => product, :price => product.price
    @cart.recalculate_price!
    flash[:notice] = "Item added to cart!"
    redirect_to '/cart'
  end

  def remove
    item = @cart.line_items.find(params[:id])
    item.destroy
    @cart.recalculate_price!
    flash[:notice] = "Item removed from cart"
    redirect_to '/cart'
  end

  def checkout
    @cart.checkout!
    session.delete(:cart_id)
    flash[:notice] = "Thank you, we will contact you within 30 minutes for confimation"
    redirect_to "/"
  end

  protected

  def find_cart
    @cart = session[:cart_id] ? Order.find(session[:cart_id]) : current_user.orders.build
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @products_by_author = @products.group_by(&:author)
  end



  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully."
      redirect_to_target_or_default(products_path)
    else
      flash.now[:error] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing up! You are now logged in."
      redirect_to products_url
    else
      render :action => 'new'
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :salt, :encrypted_password, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_sidebar_links.html.erb
This is the demo app for <%= link_to "Active Admin", "http://activeadmin.info" %>.
Don't hesitate to check out the
<%= link_to("source code for this page", "https://github.com/activeadmin/demo.activeadmin.info/blob/master/app/admin/#{model}.rb") %>,
the <%= link_to("Documentation", "http://activeadmin.info/docs/documentation.html") %>
and the <%= link_to("Github Repo", "https://github.com/activeadmin/activeadmin") %>.

app/views/cart/show.html.erb
<%= content_for(:title, "Your cart") %>
<h1>Your Cart</h1>

<% unless @cart.line_items.any? %>
  <p>You don't have any items in your cart. <%= link_to "Go Add Some", products_path %>
<% end %>

<table width="100%">
  <tr>
    <th>Product</th>
    <th>Price</th>
  </tr>
  <% for line_item in @cart.line_items %>
    <tr>
      <td><%= line_item.product.title %></td>
      <td><%= number_to_currency line_item.price %></td>
      <td><%= link_to "Remove", remove_from_cart_path(line_item), :method => :post %></td>
    </tr>
  <% end %>
  <tr>
    <td>Total:</td>
    <td><%= number_to_currency @cart.total_price %></td>
  </tr>
</table>

<hr />
<%= form_tag checkout_path, :style => "text-align: right" do |f| %>
  <%= link_to "Continue Shopping", root_path %>
  or
  <%= submit_tag "Checkout Now!" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ActiveadminDepot" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>

  <body class="metrouicss">

      <div class="nav-bar">
        <div class="nav-bar-inner padding10">
          <span class="pull-menu"></span>

          <a href="/">
            <span class="element brand">
              <span class="back-button white place-left"></span>
              <span class="name2">Shear Edge</span>
            </span>
          </a>

          <ul class="menu" style="padding-top: 10px;">
            <li><%= link_to "Home", "/" %></li>

            <li data-role="dropdown">
              <a href="#">Menu</a>
              <ul class="dropdown-menu">
                <li><%= link_to "Link1", "/path1" %></li>
                <li><%= link_to "Link2", "/path2" %></li>
                <li class="divider"></li>
                <li><%= link_to "Link3", "/path3" %></li>
              </ul>
            </li>
          </ul>
        </div>



        <div class="page-region-content">
          <div class="page-region">


          <div class="grid">
            <div class="row">

              <div id="container">


                <div id="auth">
                  <% if logged_in? %>
                      Welcome <%= current_user.username %>! Not you?
                      <%= link_to "Log out", logout_path %>

                  <% else %>
                      <%= link_to "Sign up", signup_path %> or
                      <%= link_to "Log in", login_path %>.
                  <% end %>
                </div>
               <br/>
                <br/>
                <br/>


                <% flash.each do |name, msg| %>
                    <%= content_tag :div, msg, :id => "flash_#{name}" %>
                <% end %>
                <%= content_tag :h2, yield(:title) if show_title? %>
                <%= yield %>

            </div>
          </div>
        </div>
      </div>
</div>
      <div class="nav-bar">
          <div class="nav-bar-inner" style="padding: 10px 10px 5px;">
            <span class="element">&copy; Agile Creative Consulting 2015</span>
          </div>
        </div>

    </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->


    <%= javascript_include_tag "application" %>
     </body>
  <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-23306458-2']);
      _gaq.push(['_trackPageview']);

      (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
  </script>
</html>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/products/index.html.erb
<%= content_for(:title, "Services") %>
<h1>Make your selection</h1>


<br/>

<% @products.each do |product| %>


    <div class="tile selected">

      <div class="group">

        <%= link_to(image_tag("products/" + product.image_file_name), product_path(product)) %>

        <div class="brand" style=" background: rgba(45, 137, 239, 0.7); font-size: small;">
          <span class=" text-center ">
        <%= link_to product.title + " " + "by" + " " + product.author, product_path(product) %>
</span>
        </div>
      </div>
    </div>

<% end %>

<div style="clear:both"></div>

app/views/products/show.html.erb
<% title @product.title %>

<div style="display: inline-block;">
<%= image_tag "products/#{@product.image_file_name}", :id => "product-image" %>

  <div id="product-description">
  <% if @product.description %>
      <%= simple_format @product.description %>
  <% else %>
      <p><em>No Description</em></p>
  <% end %>

  <p>
    <strong>Price:</strong>
    <%= number_to_currency @product.price %>
    (<%= link_to "Add to Cart", add_to_cart_path(@product.id) %>)
  </p>

  <p>
    <strong>By:</strong>
    <%= @product.author %>
  </p>

  <p> <%= link_to "Back to All Services", products_path %> </p>
</div>
</div>



<div style="display: inline-block;"> </div>
  <div style="clear:both;"></div>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address(xxx@xxxxxxx.com)" %><br />
    <%= f.text_field :email %>
  </p>
    <p>
      <%= f.label :phone, "Phone Number(xxx-xxx-xxxx)" %><br />
      <%= f.text_field :phone %>
    </p>
  <p>
    <%= f.label :password, "Enter password greater than 4 characters" %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit "Sign up" %></p>
<% end %>